version: '3'
services:
  nginx_load_balancer:
    image: nginx
    build: ./nginx
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '4000:4000'
      - '80:8080'
  service1:
    image: node-app
    build: ./backend
    environment: 
      APPID : backend_service1
      PORT : 1111
      DB_HOST : db_postgresql
      DB_USER : postgres
      DB_NAME : ujikom
      DB_PASS : 123
      DB_PORT : 5432
      API_KEY : B1smill4hUJIKOM
  service2:
    image: node-app
    build: ./backend
    environment: 
      APPID : backend_service2
      PORT : 2222
      DB_HOST : db_postgresql
      DB_USER : postgres
      DB_NAME : ujikom
      DB_PASS : 123
      DB_PORT : 5432
      API_KEY : B1smill4hUJIKOM
  service3:
    image: node-app
    build: ./backend
    environment: 
      APPID : backend_service3
      PORT : 3333
      DB_HOST : db_postgresql
      DB_USER : postgres
      DB_NAME : ujikom
      DB_PASS : 123
      DB_PORT : 5432
      API_KEY : B1smill4hUJIKOM
  db_postgresql:
    image: postgres
    container_name: db_postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always