-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.comments
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    message character varying(512) COLLATE pg_catalog."default",
    user_id bigint,
    timestamps timestamp with time zone NOT NULL DEFAULT now(),
    parent_id bigint,
    pelajaran_id bigint,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.hadir
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    pelajaran_id bigint NOT NULL,
    siswa_id bigint NOT NULL,
    status bigint,
    guru_id bigint NOT NULL,
    timestamps timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT hadir_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pelajaran
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nama character varying(32) COLLATE pg_catalog."default" NOT NULL,
    kelas character varying(32) COLLATE pg_catalog."default",
    guru_id bigint,
    waktu timestamp without time zone NOT NULL DEFAULT now(),
    materi character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT pelajaran_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username character varying(24) COLLATE pg_catalog."default" NOT NULL UNIQUE,
    password character varying(500) COLLATE pg_catalog."default" NOT NULL,
    email character varying(64) COLLATE pg_catalog."default" UNIQUE,
    token character varying(128) COLLATE pg_catalog."default",
    image character varying(124) COLLATE pg_catalog."default",
    roles bigint DEFAULT 1,
    nama character varying(64) COLLATE pg_catalog."default",
    kelas character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
END;